Add Dockerfile min to CI
TileDB-Inc/TileDB-MariaDB pull request #131
Opened 2020-12-23 08:33 UTC by antalakas

2020-12-23 10:52 UTC, Shelnutt2 requested changes

2020-12-23 10:52 UTC, Shelnutt2 commented on azure-pipelines.yml
> +            repository: tiledb/tiledb-mariadb
Please update the upstream name. This is were the image is pushed to.

2020-12-23 18:07 UTC, antalakas commented on azure-pipelines.yml
> +            repository: tiledb/tiledb-mariadb
👍

2020-12-24 12:22 UTC, Shelnutt2 approved these changes

2020-12-24 12:59 UTC, merged