Dstara/aggregates pushdown
TileDB-Inc/TileDB-MariaDB pull request #309
Opened 2024-01-19 14:34 UTC by DimitrisStaratzis

Description incoming

2024-01-19 17:32 UTC, Shelnutt2 commented on mytile/ha_mytile.cc
> +bool tile::mytile::has_aggregate(THD *thd, const std::string &field,
Instead of passing `aggregate_str` by reference lets use a tuple return with a std::optional. Also I suggest instead of a string we use an enum or the tiledb (or mariadb) enum for the aggregates. This way we aren't having strings inline we are doing comparisons against.

2024-01-19 17:45 UTC, Shelnutt2 commented on mytile/ha_mytile.cc
> +            DBUG_RETURN(tile::sysvars::enable_avg_aggregate_pushdown(thd));
Why is this different that the others?

2024-01-19 17:45 UTC, Shelnutt2 commented on mytile/ha_mytile.cc
> +        DBUG_RETURN(attr.cell_val_num() == 1);
@KiterLuc or @robertbindar  are var length fields supported in aggregates?

2024-01-19 17:51 UTC, KiterLuc commented on mytile/ha_mytile.cc
> +        DBUG_RETURN(attr.cell_val_num() == 1);
For a list of supported input datatypes and what their respective output datatypes are, see https://docs.tiledb.com/main/background/internal-mechanics/aggregates. In summary, we support var size inputs for min/max, var size nullable inputs for null count. The only time we output a var size value is for min/max on strings.

2024-01-19 17:57 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +        DBUG_RETURN(attr.cell_val_num() == 1);
Hey, thanks for the comment! I know they are supported but mytile does not support them. Multi valued attributes are handled like BLOBs. So if mytile reads a multi valued attribute, it sets the type to BLOB and stores the raw bytes. Not sure how aggregates can work like this..

2024-01-19 17:59 UTC, Shelnutt2 commented on mytile/ha_mytile.cc
> +        DBUG_RETURN(attr.cell_val_num() == 1);
String/varchar should be supported.
count/count null should be supported for all types
max/min/avg should return not supported

2024-01-22 00:17 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +            DBUG_RETURN(tile::sysvars::enable_avg_aggregate_pushdown(thd));
AVG and SUM require the user to enable them as they can have an effect in the types assigned to fields by mytile. Enabling them will promote all numeric types to double. Please see description for a detailed explanation of that.

2024-01-24 17:45 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +bool tile::mytile::has_aggregate(THD *thd, const std::string &field,
Done! I am now using the ```Item_sum::sumfunctype``` enum from MariaDB.

2024-01-25 13:39 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +        DBUG_RETURN(attr.cell_val_num() == 1);
String attributes are supported now!

2024-01-26 18:58 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +      tiledb_attribute_get_nullable(ctx.ptr().get(), attr.ptr().get(),
Yes there is, I have implemented it this way to keep the same style as the other cases in this method. I will switch to the C++ AP in all of them, it will make the implementation cleaner.

2024-01-27 17:59 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +      tiledb_attribute_get_nullable(ctx.ptr().get(), attr.ptr().get(),
Done!

2024-02-06 16:01 UTC, robertbindar requested changes
Thanks for the great work @DimitrisStaratzis, I'm very sure this wasn't easy.
I do believe though that the current implementation is so limiting that it would be very hard to use in practice. This limitation comes mostly from using the MariaDB structures in a way they weren't intended to be used for this, I proposed in a comment below what I think the correct approach should look like.

I think this new approach should help remove most limitations you listed below. But there are 2 we need to clarify:
1) Can you please explain why aggregates won't work for joins?
2) I will investigate a bit further because it's a bit unclear to me the issue with data type promotion for some aggregates and if we really need the setting to get everything as double.

2024-02-07 13:54 UTC, robertbindar commented
> Thanks for the great work @DimitrisStaratzis, I'm very sure this wasn't easy. I do believe though that the current implementation is so limiting that it would be very hard to use in practice. This limitation comes mostly from using the MariaDB structures in a way they weren't intended to be used for this, I proposed in a comment below what I think the correct approach should look like.
> 
> I think this new approach should help remove most limitations you listed below. But there are 2 we need to clarify:
> 
> 1. Can you please explain why aggregates won't work for joins?
@DimitrisStaratzis ?
> 2. I will investigate a bit further because it's a bit unclear to me the issue with data type promotion for some aggregates and if we really need the setting to get everything as double.

After some more investigation, it seems to me that the issue isn't impossible to fix, MariaDB promotes the datatype of AVG results as well, please see `Item_sum_avg::create_tmp_field` in `server/sql/item_sum.cc`, seems like a very good point to start deep diving. It's either you need to store a sum and a count as string in the AVG item (and MariaDB will compute at the sql layer the average) or the current code is using the incorrect table_share (or incorrect field) to store the average result, use that function as a starting point, I'm sure you'll end up with an answer.
The problem with your approach in this PR isn't only the sysvar to special case the AVG function, it's the fact that if you'd need to average a huge number of integers, summing that huge number as FLOAT64 and dividing by the count in the end would give you a pretty different result than averaging over the same sequence of numbers as integers and this is not acceptable in my opinion for a database.

2024-03-05 18:45 UTC, DimitrisStaratzis commented
I am aware of the code repetition in the new ```init_scan()```. This will be resolved tomorrow.```std::cout```s will be removed as well of course.

2024-03-05 18:57 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +  // todo massive code repetition here, will create a method
Will resolve this

2024-03-06 16:51 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +  // todo massive code repetition here, will create a method
Done!

2024-03-15 12:42 UTC, robertbindar requested changes
This is great work @DimitrisStaratzis and it'll serve as a very good foundation for future aggregate support extensions and group bys, cheers!
Let me know if you need clarifications for any of the comments below.

2024-03-15 12:42 UTC, robertbindar commented on mytile/ha_mytile.cc
> +      List_iterator_fast<Item> it(select_lex->item_list);
Please note that `select_lex` might not contain the aggregates in the item list, AFAIK that is supposed to be read from MariaDB `Query` passed at group by handler creation.

2024-03-15 12:42 UTC, robertbindar commented on mytile/ha_mytile.cc
> -    this->subarray =
cheers for isolating this build subarray chunk into a standalone function.

2024-03-15 12:42 UTC, robertbindar commented on mytile/ha_mytile.cc
> +    this->subarray =
make_unique?

2024-03-15 12:42 UTC, robertbindar commented on mytile/ha_mytile.cc
> +     const uint64_t open_at) : group_by_handler(thd_arg, mytile_hton), aggr_array(array), ctx(context), tiledb_qc(qc), valid_ranges(val_ranges), valid_in_ranges(val_in_ranges), pushdown_ranges(ranges
one intialization per line? it's very hard to follow now.

2024-03-15 12:42 UTC, robertbindar commented on mytile/ha_mytile.cc
> +      if (isp && !field_is_aggregation_compatible(
I don't like suggesing names, but `field_is_aggregation_compatible` is pretty confusing, maybe try `aggregate_is_supported()`?

2024-03-15 12:42 UTC, robertbindar commented on mytile/ha_mytile.cc
> +          if (aggr_array != nullptr && aggr_array->is_open()){
just make `aggr_array` a `shared_ptr`, here and inside the group_by handler, it'll help you get rid of this resource release uggliness.

2024-03-15 12:42 UTC, robertbindar commented on mytile/ha_mytile.cc
> +  if (select_lex->with_sum_func) {
as I wrote below for `has_aggregates`, I don't think `thd->lex->current_select` is the intended way to get all aggregate items, it might be that we'll miss some cases and the only way to notice is performance degradation because MariaDB will do the aggregates anyway.
Also please refactor so that all the `while` loops looking for aggregates stay in a single function `has_aggregates` or something similar.

2024-03-15 12:42 UTC, robertbindar commented on mytile/ha_mytile.cc
> +static bool field_is_aggregation_compatible(const std::string field, const Item_sum::Sumfunctype aggregate, tiledb::Array* array_for_comp) {
name change suggested below.

2024-03-15 12:42 UTC, robertbindar commented on mytile/ha_mytile.cc
> +    return false; // todo temporarily disable dim aggr pushdown shortcut-42339. Just remove after testing
I fixed this recently. Also aggregate on dimensions for dense was added but file as followup.

2024-03-15 12:42 UTC, robertbindar commented on mytile/ha_mytile.cc
> +        switch (type) {
this is as nasty as it gets, please see if you can use `tiledb/type/apply_with_type.h` to get rid of this inner switch case over TileDB types or at the minimum put it in a separate function.

2024-03-15 12:42 UTC, robertbindar commented on mytile/ha_mytile.cc
> +          operation = std::make_unique<tiledb::ChannelOperation>(tiledb::QueryExperimental::create_unary_aggregate<tiledb::MaxOperator>(*aggr_query, column_with_aggregate));
break lines

2024-03-15 14:10 UTC, DimitrisStaratzis commented on mysql-test/mytile/t/aggregates.test
> +select SUM(a) from dense one JOIN dense two USING(a) where one.a > 10;
Yes, they do!

2024-03-15 14:31 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +    // Dense arrays do not support query conditions
Query Conditions in Dense arrays are not allowed in mytile because the result buffers from TileDB, contain fill values for the filtered out values. So we don't allow them because a mariadb user is expecting to see only the values they requested. 

However, when we have an aggregate on a Dense array we do need to apply the query condition to the Query so that the aggregation produces the correct result.

2024-03-15 14:34 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +                DBUG_RETURN(Item_sum::SUM_FUNC);
It is. This function is only used to determine if we should push a QC to a dense array. COUNT in a dense array should not be pushed down because the QC does not fiter out results, but rather returns fill values. This causes the TIleDB count to count all values. I discussed this with @KiterLuc . This is the expecte dbehavior from core at the moment

2024-03-15 14:35 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +                DBUG_RETURN(Item_sum::SUM_FUNC);
However, to make the code more clear, I have added the count case in this method and I check in ```cold_push_func()``` if it is a Dense & COUNT() case which we can;t cimpute at the moment

2024-03-15 14:41 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +    this->subarray =
Yes, this was a unique pointer before my PR, so I left it this way

2024-03-15 15:13 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +      List_iterator_fast<Item> it(select_lex->item_list);
I know but this method is part of the mytile handler and it is only used when we create the query conditions. (They are created in the mytile handler). So I am currently unaware on how I can get access to the ```Query```

2024-03-15 15:14 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +      List_iterator_fast<Item> it(select_lex->item_list);
The ```select_lex``` is taken from the thd so I don't see a reason as to why it might not include all aggregate items

2024-03-15 15:16 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +          if (aggr_array != nullptr && aggr_array->is_open()){
It crashes if I do that, I have no clue why...

2024-03-15 15:28 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +  if (select_lex->with_sum_func) {
1. see my response above
2. I don't see how I can combine all the different while loops, they all do very different things..

2024-03-15 16:50 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +        switch (type) {
refactored!

2024-03-27 14:41 UTC, robertbindar commented on mytile/ha_mytile.cc
> +    // Dense arrays do not support query conditions
it makes sense, thanks.

2024-03-27 14:45 UTC, robertbindar commented on mytile/ha_mytile.cc
> +                DBUG_RETURN(Item_sum::SUM_FUNC);
and the QC disables computing the COUNT from frag meta if pushed down, I see now, thanks for the explanation.

2024-03-27 14:53 UTC, robertbindar commented on mytile/ha_mytile.cc
> +          if (aggr_array != nullptr && aggr_array->is_open()){
can you get a stacktrace so maybe we catch fast why that's happening? I'd be nice to fix this before merging.

2024-03-27 15:25 UTC, robertbindar commented on mytile/ha_mytile.cc
> +  if (select_lex->with_sum_func) {
yeah, you're right, it's not as straightforward as I initially say, I'll mark as resolved, thanks.

2024-03-27 15:30 UTC, robertbindar approved these changes
Nice work! Let's try to figure out if we can fix the crash on `aggr_array` as shared_ptr, it'd be a shame to rush last minute and merge that thing, other than that, ready to merge!

2024-03-27 16:56 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +          if (aggr_array != nullptr && aggr_array->is_open()){
```
0   mariadbd                            0x00000001067f3d3b my_print_stacktrace + 75
0   mariadbd                            0x00000001058338a7 handle_fatal_signal + 871
0   libsystem_platform.dylib            0x00007ff81741ec1d _sigtramp + 29
0   ???                                 0x0000600000000400 0x0 + 105553116267520
0   libsystem_c.dylib                   0x00007ff81733dca5 abort + 123
0   libc++abi.dylib                     0x00007ff8173ae082 abort_message + 241
0   libc++abi.dylib                     0x00007ff81739f225 _ZL28demangling_terminate_handlerv + 242
0   libobjc.A.dylib                     0x00007ff81709e02b _ZL15_objc_terminatev + 104
0   libc++abi.dylib                     0x00007ff8173ad4a5 _ZSt11__terminatePFvvE + 8
0   libc++abi.dylib                     0x00007ff8173ad456 _ZSt9terminatev + 54
0   ha_mytile.so                        0x0000000109c837a5 _ZN6tiledb5ArrayD1Ev + 21
0   ha_mytile.so                        0x0000000109c83785 _ZNSt3__112__destroy_atB6v15006IN6tiledb5ArrayELi0EEEvPT_ + 21
0   ha_mytile.so                        0x0000000109c83765 _ZNSt3__110destroy_atB6v15006IN6tiledb5ArrayELi0EEEvPT_ + 21
0   ha_mytile.so                        0x0000000109c83749 _ZNSt3__116allocator_traitsINS_9allocatorIN6tiledb5ArrayEEEE7destroyB6v15006IS3_vvEEvRS4_PT_ + 25
0   ha_mytile.so                        0x0000000109c827ce _ZNSt3__120__shared_ptr_emplaceIN6tiledb5ArrayENS_9allocatorIS2_EEE16__on_zero_sharedEv + 46
0   ha_mytile.so                        0x0000000109c30dd1 _ZNSt3__114__shared_count16__release_sharedB6v15006Ev + 49
0   ha_mytile.so                        0x0000000109c30d79 _ZNSt3__119__shared_weak_count16__release_sharedB6v15006Ev + 25
0   ha_mytile.so                        0x0000000109c78b1c _ZNSt3__110shared_ptrIN6tiledb5ArrayEED2B6v15006Ev + 44
0   ha_mytile.so                        0x0000000109c13f25 _ZNSt3__110shared_ptrIN6tiledb5ArrayEED1B6v15006Ev + 21
0   ha_mytile.so                        0x0000000109c5f9d5 _ZN4tile23mytile_group_by_handlerD2Ev + 117
0   ha_mytile.so                        0x0000000109c30765 _ZN4tile23mytile_group_by_handlerD1Ev + 21
0   ha_mytile.so                        0x0000000109c30789 _ZN4tile23mytile_group_by_handlerD0Ev + 25
0   mariadbd                            0x0000000105d5985c _ZN14Pushdown_queryD2Ev + 44
0   mariadbd                            0x0000000105d2d835 _ZN14Pushdown_queryD1Ev + 21
0   mariadbd                            0x0000000105d1907b _ZN4JOIN7cleanupEb + 1195
0   mariadbd                            0x0000000105d18985 _ZN4JOIN7destroyEv + 229
0   mariadbd                            0x0000000105df667e _ZN13st_select_lex7cleanupEv + 766
0   mariadbd                            0x0000000105ceb318 _Z12mysql_selectP3THDP10TABLE_LISTR4ListI4ItemEPS4_jP8st_orderS9_S7_S9_yP13select_resultP18st_select_lex_unitP13st_select_lex + 1688
0   mariadbd                            0x0000000105cea9e8 _Z13handle_selectP3THDP3LEXP13select_resulty + 552
0   mariadbd                            0x0000000105c7e663 _ZL21execute_sqlcom_selectP3THDP10TABLE_LIST + 2243
0   mariadbd                            0x0000000105c71128 _Z21mysql_execute_commandP3THDb + 6744
0   mariadbd                            0x0000000105c671c7 _Z11mysql_parseP3THDPcjP12Parser_state + 1015
0   mariadbd                            0x0000000105c63775 _Z16dispatch_command19enum_server_commandP3THDPcjb + 5365
0   mariadbd                            0x0000000105c68517 _Z10do_commandP3THDb + 3543
0   mariadbd                            0x0000000105eb4c76 _Z24do_handle_one_connectionP7CONNECTb + 406
0   mariadbd                            0x0000000105eb49ca handle_one_connection + 90
0   mariadbd                            0x000000010616af8f pfs_spawn_thread + 319
0   libsystem_pthread.dylib             0x00007ff8173f4259 _pthread_start + 125
0   libsystem_pthread.dylib             0x00007ff8173efc7b thread_start + 15
```

2024-03-27 16:57 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +          if (aggr_array != nullptr && aggr_array->is_open()){
I have absolutely no idea why this is happening..

2024-03-27 16:58 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +          if (aggr_array != nullptr && aggr_array->is_open()){
This is after just replacing the creation of the array from ```new``` to a ```shared_ptr```

2024-03-27 18:50 UTC, DimitrisStaratzis commented on mytile/ha_mytile.cc
> +          if (aggr_array != nullptr && aggr_array->is_open()){
I think I am going to leave this as is for now, let me know if you have any objections. I will come back

2024-03-28 12:19 UTC, merged