build TileDB in DockerFiles with debug info
TileDB-Inc/TileDB-MariaDB pull request #346
Opened 2024-06-05 13:27 UTC by DimitrisStaratzis

2024-06-05 13:37 UTC, Shelnutt2 commented on docker/Dockerfile-min
> +&& make -j2 \
Can we do `make -j$(nproc)` everywhere?

2024-06-05 15:38 UTC, teo-tsirpanis commented on docker/Dockerfile-min
> +&& sudo make -C tiledb install \
```suggestion
&& cmake \
  -DCMAKE_INSTALL_PREFIX=/usr/local/ \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DTILEDB_S3=ON \
  -DTILEDB_VERBOSE=ON \
  -DTILEDB_AZURE=ON \
  -DTILEDB_GCS=ON \
  -DTILEDB_HDFS=ON \
  -DTILEDB_SERIALIZATION=ON \
  -DTILEDB_WEBP=ON \
  -DTILEDB_TESTS=OFF \
  -DTILEDB_VCPKG_BASE_TRIPLET=x64-linux \
  .. \
&& sudo make -j$(nproc) tiledb install-tiledb \
```

* The vcpkg target triplet is not needed if specifying the base triplet.
* Updated the invocation of `make` to be future-proof when the superbuild gets removed, see TileDB-Inc/TileDB-Go#316

2024-06-20 10:37 UTC, dudoslav requested changes
Can you post output of `make VERBOSE=1` or some proof that `libtiledb.so` is compiled with Debug symbols and is not stripped?

2024-06-21 07:57 UTC, dudoslav commented
For example, for TileDB-Vector-Search compiled with RelWithDebInfo build type we can see:
```
base) taco:vector_search dudoslav$ objdump -h _tiledbvspy.cpython-310-x86_64-linux-gnu.so | grep debug
 27 .debug_aranges 00018ff0  0000000000000000  0000000000000000  006ee25b  2**0
 28 .debug_info   0215f43e  0000000000000000  0000000000000000  0070724b  2**0
 29 .debug_abbrev 0000ba35  0000000000000000  0000000000000000  02866689  2**0
 30 .debug_line   0060d156  0000000000000000  0000000000000000  028720be  2**0
 31 .debug_str    02ef5fba  0000000000000000  0000000000000000  02e7f214  2**0
 32 .debug_line_str 000020c1  0000000000000000  0000000000000000  05d751ce  2**0
 33 .debug_loclists 00d6702c  0000000000000000  0000000000000000  05d7728f  2**0
 34 .debug_rnglists 0026651f  0000000000000000  0000000000000000  06ade2bb  2**0

and:

(base) taco:vector_search dudoslav$ file _tiledbvspy.cpython-310-x86_64-linux-gnu.so
_tiledbvspy.cpython-310-x86_64-linux-gnu.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=f0582f2ec9c3b5652afa951a2326eaa405505df8, with debug_info, not stripped
```

2024-06-21 10:54 UTC, dudoslav commented
I believe that we do not produce debug info because we use Dockerfiles that download MYTILE from releases and not from this branch. So after merge they should contain debug info, otherwise rework of Dockerfiles is needed. I would suggest to rework those Dockerfiles, maybe we could create a shortcut task for that.

2024-06-21 11:04 UTC, dudoslav commented
When using Dockerfile-dev that uses local changes I can see:
```
mysql@c5fa78c1a064:/usr/lib$ file libtiledb.so.2.24
libtiledb.so.2.24: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=98aa1eb6236d4ccad123623fabd3dceb0c1f7861, with debug_info, not stripped
```

So it seems like it should work, but keep in mind, that only after we change the release version in all dockerfiles.

2024-06-21 11:04 UTC, dudoslav approved these changes

2024-06-21 11:52 UTC, DimitrisStaratzis commented
Thank you @dudoslav for helping me with this!

2024-06-21 12:41 UTC, merged