Revert "Revert "Fix leak of `mytile_group_by_handler::aggr_array`. (#374)""
TileDB-Inc/TileDB-MariaDB pull request #379
Opened 2024-09-18 10:26 UTC by teo-tsirpanis

Reverts TileDB-Inc/TileDB-MariaDB#376

It was determined that #374 is not the cause of the subsequently observed failures.

2024-09-18 10:30 UTC, DimitrisStaratzis requested changes
The mytile version is downgraded here because we also included the bump in that PR. Not a big deal since we will merge the 0.34.2 bump after this but let's remove these changes

2024-09-18 10:30 UTC, DimitrisStaratzis commented on docker/Dockerfile
> +ARG MYTILE_VERSION="0.34.0"
The mytile version is downgraded here because we also included the bump in that PR. Not a big deal since we will merge the 0.34.2 bump after this but let's remove these changes

2024-09-18 10:33 UTC, teo-tsirpanis commented on docker/Dockerfile
> +ARG MYTILE_VERSION="0.34.0"
Done.

2024-10-01 13:18 UTC, Shelnutt2 approved these changes

2024-10-01 13:18 UTC, merged